### ISSUE TITLE
[BUG] Tom Select SCSS compilation fails with Tabler 1.5.1

### ISSUE THREAD

**Issue by anthonyL05** [tabler/tabler#3069]
### Tabler version

1.5.1

### Browser

N/A – build-time SCSS compilation issue

### OS

Linux

### Screen size

bug de compilation

### Describe the bug

Describe the bug

After upgrading @tabler/core from 1.4.0 to 1.5.1, SCSS compilation fails when importing Tom Select's Bootstrap 5 stylesheet.

Tabler 1.5.1 defines $border-color as a CSS custom property:

$border-color: var(--gray-200) !default;

Tom Select 2.6.2 uses $border-color for $select-color-item-border and later passes it to Sass color.adjust().

This results in the following compilation error:

$color: var(--gray-200) is not a color.

node_modules/tom-select/dist/scss/_items.scss

Pinning @tabler/core back to 1.4.0 fixes the issue without any other changes.

Environment:

@tabler/core: 1.5.1
tom-select: 2.6.2
bootstrap: 5.3.8
sass: 1.104.1
sass-loader: 17.0.1
Node.js: 22.23.2

### How to reproduce

Install @tabler/core@1.5.1 and tom-select@2.6.2.
Import Tabler SCSS.

Import Tom Select's Bootstrap 5 SCSS:

@import "~tom-select/dist/scss/tom-select.bootstrap5";
Compile the SCSS.
Compilation fails in tom-select/dist/scss/_items.scss when color.adjust() receives var(--gray-200) instead of a Sass color.

Downgrading only @tabler/core from 1.5.1 to 1.4.0 makes the same build compile successfully.

### Screenshots

<img width="1797" height="775" alt="Image" src="https://github.com/user-attachments/assets/92524cee-ab5f-405c-99be-fea69025f222" /> . Voila le screenshot de l'erreur exact, je l'ai reproduit sur plusieurs environement

**Comment by codecalm** [comment]
Thanks for the clear report. This one can't be fixed on the Tabler side. Tom Select's `tom-select.bootstrap5.scss` takes Bootstrap's `$border-color` and runs it through `color.adjust()`, and since 1.5 that variable holds `var(--gray-200)`, which Sass can't treat as a color.

There are two ways around it. The easy one is to use the compiled `tom-select.bootstrap5.css` instead of the Sass sources. If you'd rather keep compiling, set the two variables Tom Select adjusts to plain colors before the import:

```scss
@use '@tabler/core/scss/tabler' as *;

$select-color-text: #182433;
$select-color-item-border: #e6e7e9;
@import 'tom-select/dist/scss/tom-select.bootstrap5';
```

The `as *` part matters, because a plain `@use` doesn't expose Tabler's variables to the `@import` that follows. I've added this to the upgrade guide and the Advanced select docs in a65771caa (will show up on docs.tabler.io with the next deploy).

**Comment by codecalm** [comment]
Closing this one. The workaround is now in the docs, in the upgrade guide and on the Advanced select page, and there's nothing to fix in Tabler itself. Reopen if the override from my earlier comment doesn't compile for you.
