### ISSUE TITLE
[BUG] Combining jQuery-slim and Selectize

### ISSUE THREAD

**Issue by PerryvanderMeer** [tabler/tabler#721]
Combining the jQuery-slim-version with Selectize produces an javascript error:
`TypeError: self.$dropdown_content.stop is not a function`

Please use the regular jQuery.min-version instead of jQuery-slim.min.

See: https://github.com/selectize/selectize.js/issues/1308

**Comment by codecalm** [comment]
Hi @PerryvanderMeer,

we are working on other libraries, which doesn't use jQuery. Soon we'll release new version :)

**Comment by FreexD** [comment]
Tabler has switched to reqular jQuery for now ;) It works in 1.0.0-alpha.15 ;) We'll be however getting rid of selectize since it uses jQuery and bootstrap v5 does not, so I would not rely on that too much.

https://github.com/tabler/tabler/issues/625
